export enum TypeSemestre {
  SEMESTRE_1 = 'SEMESTRE_1',
  SEMESTRE_2 = 'SEMESTRE_2',
  SEMESTRE_3 = 'SEMESTRE_3',
  SEMESTRE_4 = 'SEMESTRE_4',
  SEMESTRE_5 = 'SEMESTRE_5',
  SEMESTRE_6 = 'SEMESTRE_6'
}
